{
 "title": "SRE Overview",
 "tags": [
  "SRE",
  "Nginx",
  "CF",
  "Kafka",
  "EFK",
  "latest"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Nginx VM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(avg(nginxplus_up{job=\"NginxPlus_NonpciAPI\"}))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "API CPU Usage (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - avg by (instance)(rate(node_cpu_seconds_total{job=\"NodeExporter_NonpciAPI\", mode=\"idle\"}[1m]) * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "WWW CPU Usage (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", job=\"NodeExporter_WWW\"}[5m])) * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "WWW",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(avg(nginxplus_up{job=\"NginxPlus_WWW\"}))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Mobile",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(avg(nginxplus_up{job=~\"NginxPlus_MobileCMS\"}))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Customer",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(avg(nginxplus_up{job=\"NginxPlus_CgridAPI\"}))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Inventory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(avg(nginxplus_up{job=\"NginxPlus_InventoryAPI\"}))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "API Server Zone Status Code Responses (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 2, "y": 9 },
   "targets": [
    {
     "expr": "round(sum(increase(nginxplus_server_zone_responses{job=\"NginxPlus_NonpciAPI\"}[5m]) != 0) by (code))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes{job=\"NodeExporter_NonpciAPI\"} - node_memory_MemFree_bytes{job=\"NodeExporter_NonpciAPI\"} - node_memory_Buffers_bytes{job=\"NodeExporter_NonpciAPI\"} - node_memory_Cached_bytes{job=\"NodeExporter_NonpciAPI\"}) / node_memory_MemTotal_bytes{job=\"NodeExporter_NonpciAPI\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "WWW Server Zone Status Code Responses (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 9 },
   "targets": [
    {
     "expr": "round(sum(increase(nginxplus_server_zone_responses{job=\"NginxPlus_WWW\"}[5m]) != 0) by (code))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WWW Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes{job=\"NodeExporter_WWW\"} - node_memory_MemFree_bytes{job=\"NodeExporter_WWW\"} - node_memory_Buffers_bytes{job=\"NodeExporter_WWW\"} - node_memory_Cached_bytes{job=\"NodeExporter_WWW\"}) / node_memory_MemTotal_bytes{job=\"NodeExporter_WWW\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Microsites",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(avg(nginxplus_up{job=~\"NginxPlus_Microsites\"}))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "CMS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(avg(nginxplus_up{job=\"NginxPlus_CMSUploads\"}))",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}